### ISSUE TITLE
Sky texture isn't rotated properly

### ISSUE THREAD

**Issue by ghost** [FlashyReese/nuit-interop#1]
Dramatic Skies demo w/ FabricSkyboxes and FabricSkyboxes-interop

![2022-11-08_23 25 36](https://user-images.githubusercontent.com/63958709/200690478-a5c36043-adf9-4e5a-a37f-d7126787d28e.png)

**Comment by ghost** [comment]
Just saw the new version with the fix, sorry

**Comment by FlashyReese** [comment]
Dramatic Skies supports FSB out of the box. `fabricskyboxes-interop` will do nothing here.
