### ISSUE TITLE
FSB Interpol is broken with Sama Faithful

### ISSUE THREAD

**Issue by Lolothepro** [FlashyReese/nuit-interop#11]
![2023-06-30_16 53 11](https://github.com/FlashyReese/fabricskyboxes-interop/assets/68275908/2188b6d0-dd23-4b11-9008-81310a430318)

**Comment by FlashyReese** [comment]
![image](https://github.com/FlashyReese/fabricskyboxes-interop/assets/30311066/bb2554ce-e021-4e8a-8469-c62c8debdea2)

What versions are you running for each?

**Comment by Lolothepro** [comment]
FSB: 0.7.1
FSB Interop: 1.3.2
MC: 1.20.1

**Comment by FlashyReese** [comment]
Can you try using the build linked in this actions build? https://github.com/AMereBagatelle/fabricskyboxes/actions/runs/5365126234

**Comment by Lolothepro** [comment]
> Can you try using the build linked in this actions build? [AMereBagatelle/fabricskyboxes/actions/runs/5365126234](https://github.com/AMereBagatelle/fabricskyboxes/actions/runs/5365126234)

works (in 1.19.4)

**Comment by FlashyReese** [comment]
Sorry I linked the wrong version of Minecraft. https://github.com/AMereBagatelle/fabricskyboxes/actions/runs/5365124674

**Comment by Lolothepro** [comment]
> Sorry I linked the wrong version of Minecraft. [AMereBagatelle/fabricskyboxes/actions/runs/5365124674](https://github.com/AMereBagatelle/fabricskyboxes/actions/runs/5365124674)

it works, ty!
