### ISSUE TITLE
Custom sky colors on OptiFine packs don't work

### ISSUE THREAD

**Issue by twiilit** [FlashyReese/nuit-interop#16]
Hello! I'm using a pack called New Default+ (built for OptiFine) and for some reason the custom sky colors used there don't work when using it here.

The specific pack I'm using:
https://www.curseforge.com/minecraft/texture-packs/newdefaultplus/files/4776800

Here's the screenshots using OptiFine (how it's supposed to look):
![2023-10-11_18 13 29](https://github.com/FlashyReese/fabricskyboxes-interop/assets/69771353/422d3457-1480-43a3-9277-86b91b9288ca)
![2023-10-11_18 13 39](https://github.com/FlashyReese/fabricskyboxes-interop/assets/69771353/8810aced-3f5a-4534-b55f-885d971c8c51)

Here's the screenshots using this mod:
![2023-10-11_18 11 35](https://github.com/FlashyReese/fabricskyboxes-interop/assets/69771353/9815a9fc-5249-4a4a-ad02-f98b80c2fb5d)
![2023-10-11_18 11 57](https://github.com/FlashyReese/fabricskyboxes-interop/assets/69771353/9a21f63c-7915-43a2-b636-840308a154a3)

**Comment by twiilit** [comment]
Hello! It's absolutely much better, with the sky color now being consistent and not changing depending on where you look, but the colors still seem off for some reason.

(On 1.3.6)
![image](https://github.com/FlashyReese/fabricskyboxes-interop/assets/69771353/3e37a318-3a97-4d7f-b6f2-6a1a1a7f0741)
![image](https://github.com/FlashyReese/fabricskyboxes-interop/assets/69771353/352b5b96-7df2-45a4-81b0-220fe381d43f)

Thank you again!!

**Comment by FlashyReese** [comment]
Yeah that's due the rotation and blend being a bit different, I won't be able to translate this properly yet. Some changes need to be done to FSB first.

**Comment by twiilit** [comment]
I see. Thank you for all your work!!

**Comment by FlashyReese** [comment]
The latest version should already resolve this issue.
