### ISSUE TITLE
[Bug] Mickey Joe's Barely Default fails to load resources

### ISSUE THREAD

**Issue by Thanos1716** [FlashyReese/nuit-interop#18]
Upon loading [this](https://github.com/FlashyReese/fabricskyboxes-interop/files/13373999/MickeyJoesBarelyDefault.zip) minimum reproducible example of [this](https://legacy.curseforge.com/minecraft/texture-packs/mickey-joes-relatively-improved-default) pack, the game hangs for a second, and then sends the user to the title screen, claiming `failed to reload resources`.
This issue was reported twice [here](https://github.com/Traben-0/Entity_Model_Features/issues/54) and [here](https://github.com/Traben-0/Entity_Model_Features/issues/90) for the wrong mod.

Minecraft 1.20.2
FabricSkyBoxes 0.7.3+mc1.20.2
FSB Interop 1.3.6+mc1.20.2-build.52

**Comment by FlashyReese** [comment]
Technically that resource pack does not follow the [OptiFine specification](https://optifine.readthedocs.io/custom_sky.html#heights) properly for height [ranges](https://optifine.readthedocs.io/syntax.html#ranges). It's improperly setting ranges with `256-50` (max-min) when it should be `50-256` (min-max). I can technically account for the improper usage and check for it.
