### ISSUE TITLE
Sky Color Dulled at Sunset

### ISSUE THREAD

**Issue by S33R-OF-PYR3** [FlashyReese/nuit-interop#19]
I've been comparing the color of the sunset between vanilla, Optifine, and Fabulously Optimized and noticed the sky was significantly duller when using a skybox texture pack. I already talked to the FO discord and we determined the issue may be with the FSB mod.

Vanilla, Optifine, FO Sky (without resource pack) - Sunset:
![1](https://github.com/FlashyReese/fabricskyboxes-interop/assets/117496140/5c52925a-74ee-45ab-9af2-a4571e75d797)

Vanilla, Optifine, FO Sky (with resource pack) - Sunset:
![2](https://github.com/FlashyReese/fabricskyboxes-interop/assets/117496140/d6ebcf32-1497-48a2-8b4d-7f0aa17bd261)

Vanilla, Optifine, FO Sky (with resource pack) - Midday:
![3](https://github.com/FlashyReese/fabricskyboxes-interop/assets/117496140/8e77747e-3599-40bc-a086-5aa290fbdd81)

The most extreme difference has been observed at sunset while using FO. The resource pack has sky.properties files that utilize blend modes like screen and add for both sunset and midday texture assets. I'm not sure if how FSB is rendering the skybox or properties files is what's causing the color change. I'll also link the texture pack download below.
https://www.mediafire.com/file/vehgx673xojgm9k/S33R+Beautiful+Environment.zip/file

**Comment by FlashyReese** [comment]
https://github.com/AMereBagatelle/fabricskyboxes/issues/101

I'm currently working on a patch for this issue which shows some promise, but there are still a few things that need to be solved. However, I'm uncertain whether I'll be able to release this patch in time as I'll be away for the next four months.

**Comment by S33R-OF-PYR3** [comment]
> [AMereBagatelle/fabricskyboxes#101](https://github.com/AMereBagatelle/fabricskyboxes/issues/101)
> 
> I'm currently working on a patch for this issue which shows some promise, but there are still a few things that need to be solved. However, I'm uncertain whether I'll be able to release this patch in time as I'll be away for the next four months.

That's fine, it's a p niche visual error. I'll keep using Optifine when I need it, and I'm down to wait however long until you've implemented it.
