### ISSUE TITLE
1.16.5 versions require Java 17

### ISSUE THREAD

**Issue by the-r3dacted** [FlashyReese/nuit-interop#2]
I'm in a scenario where I'm using Java 8 and so I'm using 1.16.5. Adding the interop (the main addon is fine) causes the game to not start giving an error specifying that it needs Java 17.

**Comment by FlashyReese** [comment]
You can download the build artifact here: https://github.com/FlashyReese/fabricskyboxes-interop/actions/runs/3848937989
This will be in the next release.

**Comment by the-r3dacted** [comment]
Works great with Java 8, thanks.
