### ISSUE TITLE
Wrong custom sun/moon positions when using shaders

### ISSUE THREAD

**Issue by andywithcatz** [FlashyReese/nuit-interop#9]
![2023-05-03_20 53 43](https://user-images.githubusercontent.com/57657561/236003650-8aab2f93-f212-494e-b0f3-1c529b362d69.png)
BSL Shaders, with Misa's Resource Pack combined (and its custom shader config)

**Comment by FlashyReese** [comment]
Regrettably, there's nothing within my power to resolve the issue as there's no standard format available in OptiFine for the sun/moon feature. Shaderpacks can either create their own sun/moon or use the trajectory provided by Iris, which supports only a single sun and moon. On the other hand, FSB permits users to specify multiple suns or moons for simulating other planets, such as Tatooine.
